Fix Wouxun uv8 variants
Incorrect floating point division caused:

chirp.errors.RadioError: Failed to communicate with radio:
integer argument expected, got float